### ISSUE TITLE
Consider using a Docker volume instead of `/home/{user}/.config/gh-runner/{runner}/creds/`

### ISSUE THREAD

**Issue by pbchekin** [leshikus/gh-runner#6]
If you change your script to use a Docker volume, then the script can be used to restart a runner by different users.

**Comment by leshikus** [comment]
What is the benefit of a volume? Copying is needed anyway - you still copy credentials in `entrypoint.sh`

For multiple users I suggest an option to re-define `/home/{user}/.config/gh-runner/{runner}` to a custom one, so several people can use one storage

**Comment by pbchekin** [comment]
> For multiple users I suggest an option to re-define `/home/{user}/.config/gh-runner/{runner}` to a custom one, so several people can use one storage

Yes, please do that.
