### ISSUE TITLE
Vagrant directory is per runner, not per host

### ISSUE THREAD

**Issue by pbchekin** [leshikus/gh-runner#7]
I've noticed that script mounts `$agent_dir/vagrant` to `/runner/.vagrant.d`. That means that every runner will need to download all vagrant boxes. Also if we want to use a custom vagrant box, then we have to distribute such box across all runners on all hosts, rather than once per host.

While this is not a big issue at the moment, we need to find a good way to distribute custom vagrant boxes to all runners.

**Comment by leshikus** [comment]
We have agreed we keep it per runner
