### ISSUE TITLE
When using HTTP/HTTPS proxy the script overrides ~/.docker/config.json on the host

### ISSUE THREAD

**Issue by pbchekin** [leshikus/gh-runner#9]
This overwrites other options that present in the configuration file, such as `auths` key, so users have to login to all Docker registries again. If the script replaces ~/.docker/config.json to set HTTP/HTTPS proxy in the container, then there are two better options:

* Pass proxy to the container using environment variables (`--env HTTP_PROXY` and so on)
* Use a tool such as `jq` to create/update the existing file in place, for example:

```
[[ -f ~/.docker/config.json ]] || (echo "{}" > ~/.docker/config.json)
tmp="$(mktemp)"
jq ".proxies.default = {\"httpProxy\": \"$http_proxy\", \"httpsProxy\": \"$https_proxy\", \"noProxy\": \"$no_proxy\"}" ~/.docker/config.json > "$tmp"
mv "$tmp" ~/.docker/config.json
```

**Comment by leshikus** [comment]
Made `config.json` docker context exclusive, added --env setting for the outer docker
